Fix build for ARM
When compiling for ARM, char defaults to unsigned [1].

To avoid build and runtime issues:

* Set chars to signed explecitly when used as nombers
* Replace by bool when just used to keep a flag

Fixes build with Yocto/OE:

| gk-src/src/percussion_state.cpp: In constructor 'PercussionState::PercussionState()':
| gk-src/src/percussion_state.cpp:50:28: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]

[1] https://developer.arm.com/documentation/dui0472/m/c-and-c---implementation-details/basic-data-types-in-arm-c-and-c--

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>